-- Smart Campus Universidad Nueva Esperanza
-- Migración MySQL/phpMyAdmin -> Supabase PostgreSQL
-- Mantiene las mismas 6 tablas del modelo copo de nieve vistas en phpMyAdmin.
-- Ejecutar este archivo en Supabase: SQL Editor -> New query -> Run.

begin;

-- Limpieza opcional para reinstalar desde cero.
drop table if exists staging_lectura_cruda cascade;
drop table if exists staging_upload_batch cascade;
drop table if exists fact_consumo_energetico_pred cascade;
drop table if exists factconsumoenergetico cascade;
drop table if exists dimocupacion cascade;
drop table if exists dimtiempo cascade;
drop table if exists dimedificio cascade;
drop table if exists dimambiente cascade;

-- 1. Dimensión Ambiente: igual a MySQL
create table dimambiente (
  id_ambiente integer primary key,
  nombre varchar(50),
  tipo varchar(50),
  capacidad integer
);

-- 2. Dimensión Edificio: igual a MySQL
create table dimedificio (
  id_edificio integer primary key,
  nombre varchar(50),
  tipo varchar(50)
);

-- 3. Dimensión Ocupación: igual a MySQL, con identity para reemplazar AUTO_INCREMENT
create table dimocupacion (
  id_ocupacion integer generated by default as identity primary key,
  cantidad_personas integer,
  porcentaje integer
);

-- 4. Dimensión Tiempo: mantiene la columna "año" como en MySQL/phpMyAdmin
create table dimtiempo (
  id_tiempo integer primary key,
  hora integer,
  mes integer,
  "año" integer,
  dia_semana varchar(10)
);

-- 5. Tabla de hechos: igual a MySQL, con identity para reemplazar AUTO_INCREMENT
create table factconsumoenergetico (
  id_fact integer generated by default as identity primary key,
  id_tiempo integer references dimtiempo(id_tiempo),
  id_edificio integer references dimedificio(id_edificio),
  id_ambiente integer references dimambiente(id_ambiente),
  id_ocupacion integer references dimocupacion(id_ocupacion),
  consumo_kwh real,
  demanda_pico_kw real,
  factor_potencia real,
  temperatura real,
  eficiencia real,
  riesgo_sobreconsumo smallint
);

-- 6. Tabla de predicciones IA: igual a MySQL, con identity para reemplazar AUTO_INCREMENT
create table fact_consumo_energetico_pred (
  id integer generated by default as identity primary key,
  id_tiempo integer,
  hora integer,
  mes integer,
  anio integer,
  id_edificio integer,
  id_ambiente integer,
  ocupacion numeric(10,2),
  temperatura numeric(10,2),
  demanda_pico_kw numeric(10,2),
  factor_potencia numeric(10,3),
  consumo_kwh numeric(10,2),
  nombre_edificio varchar(100),
  tipo_ambiente varchar(100),
  nombre_mes varchar(20),
  periodo varchar(20),
  franja_horaria varchar(30),
  eficiencia_energetica_pct numeric(10,2),
  riesgo_energetico_indice varchar(30),
  pred_consumo_kwh numeric(10,2),
  sobreconsumo_real smallint,
  riesgo_sobreconsumo_prob numeric(10,4),
  riesgo_sobreconsumo_pred varchar(30),
  fecha_proceso timestamp not null default current_timestamp
);

-- Tablas técnicas para que la página conserve el flujo 1 al 7.
-- No reemplazan el modelo copo de nieve; solo registran lote y staging en nube.
create table staging_upload_batch (
  batch_id integer generated by default as identity primary key,
  nombre_lote varchar(100),
  archivos jsonb,
  estado varchar(50) default 'RECIBIDO',
  registros_crudos integer default 0,
  registros_dw integer default 0,
  registros_predichos integer default 0,
  id_fact_min integer,
  id_fact_max integer,
  creado_en timestamp default current_timestamp,
  actualizado_en timestamp default current_timestamp
);

create table staging_lectura_cruda (
  id_staging integer generated by default as identity primary key,
  batch_id integer references staging_upload_batch(batch_id) on delete cascade,
  origen_archivo varchar(255),
  id_tiempo integer,
  hora integer,
  mes integer,
  anio integer,
  id_edificio integer,
  id_ambiente integer,
  ocupacion numeric(10,2),
  temperatura numeric(10,2),
  demanda_pico_kw numeric(10,2),
  factor_potencia numeric(10,3),
  consumo_kwh numeric(10,2),
  nombre_edificio varchar(100),
  tipo_ambiente varchar(100),
  payload_json jsonb,
  creado_en timestamp default current_timestamp
);

create index idx_staging_batch on staging_lectura_cruda(batch_id);
create index idx_fact_tiempo on factconsumoenergetico(id_tiempo);
create index idx_fact_edificio on factconsumoenergetico(id_edificio);
create index idx_fact_ambiente on factconsumoenergetico(id_ambiente);
create index idx_fact_ocupacion on factconsumoenergetico(id_ocupacion);





commit;

-- Estructura limpia sin datos. Para cargar datos, usa supabase_copo_nieve_smartcampus.sql completo.
